# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='limit_of_voters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
