# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='choice',
            field=models.CharField(default='yes', max_length=100),
        ),
    ]
