# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_reason_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='choice',
            field=models.CharField(max_length=100),
        ),
    ]
