# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20180315_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='launcher',
            field=models.CharField(default='Liwei', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=100),
        ),
    ]
